"""Deterministic calibration sampling and ESP-DL deployment metadata helpers."""

from __future__ import annotations

import hashlib
import math
from collections import defaultdict
from pathlib import Path

import torch

from .data import PackedHeadDataset


def _count_bin(count: int) -> str:
    if count == 0:
        return "empty"
    if count == 1:
        return "one"
    if count <= 4:
        return "two_to_four"
    if count <= 8:
        return "five_to_eight"
    return "more_than_eight"


def _size_bin(row: dict) -> str:
    sides = [
        min(head["bbox_cache_xywh"][2:])
        for head in row["heads"]
        if not head["ignore"]
    ]
    if not sides:
        return "none"
    side = max(sides)
    if side < 12:
        return "tiny"
    if side < 24:
        return "small"
    if side < 48:
        return "medium"
    return "large"


def stratum(row: dict) -> tuple[str, str, str]:
    """Group scenes by source, crowding, and largest visible head size."""
    count = sum(not head["ignore"] for head in row["heads"])
    return row["source"], _count_bin(count), _size_bin(row)


def representative_indices(rows: list[dict], count: int, seed: int = 20260809) -> list[int]:
    """Round-robin deterministic strata rather than taking adjacent images."""
    if count < 1:
        raise ValueError("sample count must be positive")
    groups: dict[tuple[str, str, str], list[tuple[str, int]]] = defaultdict(list)
    for index, row in enumerate(rows):
        digest = hashlib.sha256(f"{seed}:{row['image_id']}".encode()).hexdigest()
        groups[stratum(row)].append((digest, index))
    for group in groups.values():
        group.sort()

    keys = sorted(
        groups,
        key=lambda key: hashlib.sha256(f"{seed}:{key}".encode()).hexdigest(),
    )
    selected = []
    depth = 0
    while len(selected) < min(count, len(rows)):
        added = False
        for key in keys:
            group = groups[key]
            if depth < len(group):
                selected.append(group[depth][1])
                added = True
                if len(selected) == min(count, len(rows)):
                    break
        if not added:
            break
        depth += 1
    return selected


class CalibrationLoader:
    """Repeatable lazy batch-one float input stream for ESP-PPQ."""

    def __init__(self, dataset: PackedHeadDataset, indices: list[int]):
        self.dataset = dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, position: int) -> torch.Tensor:
        image, _ = self.dataset[self.indices[position]]
        return image[None].float().sub_(128).div_(128)

    def __iter__(self):
        for position in range(len(self)):
            yield self[position]


def tensor_scale(value) -> float:
    """Read a scalar PPQ power-of-two scale regardless of tensor wrapper."""
    if isinstance(value, torch.Tensor):
        return float(value.detach().cpu().reshape(-1)[0])
    return float(value)


def scale_exponent(scale: float) -> int:
    exponent = round(math.log2(scale))
    if not math.isclose(scale, 2.0**exponent, rel_tol=1e-6, abs_tol=1e-12):
        raise RuntimeError(f"ESP-DL scale {scale} is not a power of two")
    return exponent


def write_c_header(path: Path, metadata: dict) -> None:
    """Write constants needed to connect camera bytes, ESP-DL, and decoder."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "#ifndef TRACKER_MODEL_CONFIG_H\n"
        "#define TRACKER_MODEL_CONFIG_H\n\n"
        "/* Generated by training/quantize.py; do not edit by hand. */\n"
        f"#define TRACKER_INPUT_WIDTH {metadata['input']['width']}\n"
        f"#define TRACKER_INPUT_HEIGHT {metadata['input']['height']}\n"
        f"#define TRACKER_INPUT_CHANNELS {metadata['input']['channels']}\n"
        f"#define TRACKER_INPUT_EXPONENT ({metadata['input']['exponent']})\n"
        f"#define TRACKER_OUTPUT_WIDTH {metadata['output']['width']}\n"
        f"#define TRACKER_OUTPUT_HEIGHT {metadata['output']['height']}\n"
        f"#define TRACKER_OUTPUT_CHANNELS {metadata['output']['channels']}\n"
        f"#define TRACKER_OUTPUT_EXPONENT ({metadata['output']['exponent']})\n"
        f"#define TRACKER_OFFSET_Q {metadata['output']['offset_q']}U\n\n"
        "#endif\n"
    )
